-- generated by derive.hs
module Prose.Internal.Hebrew_Letter where
hebrew_letter = [
    ['\x05D0'..'\x05EA'],
    ['\x05F0'..'\x05F2'],
    ['\xFB1D'],
    ['\xFB1F'..'\xFB28'],
    ['\xFB2A'..'\xFB36'],
    ['\xFB38'..'\xFB3C'],
    ['\xFB3E'],
    ['\xFB40'..'\xFB41'],
    ['\xFB43'..'\xFB44'],
    ['\xFB46'..'\xFB4F'] ]
