-- generated by derive.hs
module Prose.Internal.Katakana where
katakana = [
    ['\x3031'..'\x3035'],
    ['\x309B'..'\x309C'],
    ['\x30A0'],
    ['\x30A1'..'\x30FA'],
    ['\x30FC'..'\x30FE'],
    ['\x30FF'],
    ['\x31F0'..'\x31FF'],
    ['\x32D0'..'\x32FE'],
    ['\x3300'..'\x3357'],
    ['\xFF66'..'\xFF6F'],
    ['\xFF70'],
    ['\xFF71'..'\xFF9D'],
    ['\x1B000'] ]
