
Grapheme_Extend.hs:
	./derive.hs set ../../data/DerivedCoreProperties.txt Grapheme_Extend

SpacingMark.hs:
	./derive.hs set ../../data/GraphemeBreakProperty.txt SpacingMark

LV.hs:
	./derive.hs set ../../data/GraphemeBreakProperty.txt LV

LVT.hs:
	./derive.hs set ../../data/GraphemeBreakProperty.txt LVT

Hebrew_Letter.hs:
	./derive.hs set ../../data/WordBreakProperty.txt Hebrew_Letter

Numeric.hs:
	./derive.hs set ../../data/WordBreakProperty.txt Numeric

ALetter.hs:
	./derive.hs set ../../data/WordBreakProperty.txt ALetter

MidNum.hs:
	./derive.hs set ../../data/WordBreakProperty.txt MidNum

Katakana.hs:
	./derive.hs set ../../data/WordBreakProperty.txt Katakana

GraphemeBreakTest.hs:
	./derive.hs break-test ../../data-test/GraphemeBreakTest.txt GraphemeBreakTest

WordBreakTest.hs:
	./derive.hs break-test ../../data-test/WordBreakTest.txt WordBreakTest

NormalizationTest.hs:
	./derive.hs norm-test ../../data-test/NormalizationTest.txt NormalizationTest

