
Grapheme_Extend.hs:
	./derive.hs set ../../data/DerivedCoreProperties.txt Grapheme_Extend

SpacingMark.hs:
	./derive.hs set ../../data/GraphemeBreakProperty.txt SpacingMark

LV.hs:
	./derive.hs set ../../data/GraphemeBreakProperty.txt LV

LVT.hs:
	./derive.hs set ../../data/GraphemeBreakProperty.txt LVT

GraphemeBreakTest.hs:
	./derive.hs break-test ../../data-test/GraphemeBreakTest.txt GraphemeBreakTest
