-- generated by derive.hs
module Prose.Internal.MidNum where
midnum = [
    ['\x002C'],
    ['\x003B'],
    ['\x037E'],
    ['\x0589'],
    ['\x060C'..'\x060D'],
    ['\x066C'],
    ['\x07F8'],
    ['\x2044'],
    ['\xFE10'],
    ['\xFE14'],
    ['\xFE50'],
    ['\xFE54'],
    ['\xFF0C'],
    ['\xFF1B'] ]
